### ISSUE TITLE
[JOSS review] error when running singularity-compose-simple example

### ISSUE THREAD

**Issue by cole-brokamp** [singularityhub/singularity-compose#22]
Hello, I am using a docker container (ubuntu:18.04) to test the `singularity-compose-simple` example as in the Quick Start documentation.  I've installed singularity from source (version 2.5.2) and successfully installed `singularity-compose` with `pip`, but get the following error whenever I try to run any command, for example `singularity-compose build` within the `singularity-compose-simple` folder from the example repository:

```sh
> singularity-compose build
Traceback (most recent call last):
  File "/usr/local/bin/singularity-compose", line 7, in <module>
    from scompose.client import start
  File "/usr/local/lib/python2.7/dist-packages/scompose/client/__init__.py", line 198
    from .exec import main
             ^
SyntaxError: invalid syntax
```

Any ideas on where I could have gone wrong?

**Comment by vsoch** [comment]
There are two quick fixes here. The first is that singularity-compose won't work with python 2.x, I just can't provide support for it given end of life.

The second issue (which you haven't hit yet) is that Singularity 2.x definitely won't support instances like we need. The reason we needed to wait for the 3.x family to create this, period, is because it had very little support for networking before that.

So unfortunately to test you need both of those things updated.

**Comment by vsoch** [comment]
You also likely need to test this on a host - I haven't tried in a docker container, but given the requirements for networking, I suspect it won't work.

**Comment by vsoch** [comment]
I realize this isn't in the docs clearly stated! Just added here https://singularityhub.github.io/singularity-compose/#/?id=dependencies (open devtools to clear cache if you don't see it yet).

**Comment by cole-brokamp** [comment]
Perfect, you beat me to my own suggestion! This is super helpful for a beginner with this type of setup for me.  (I usually rely on our HPC version of Singularity, which they haven't yet upgraded to 3.0).

**Comment by cole-brokamp** [comment]
I think you are right about not working in a docker container, I'm getting an `ERROR: Failed to unshare root file system: Operation not permitted`, which I'm pretty sure would have to do with how Docker manages that.  I will try on a host this evening. Thanks for the help!

**Comment by vsoch** [comment]
I haven't tried it, but you would need to set privileged to true, and then bind the docker daemon, as is done with docker2singularity - [see the docker run example here](https://github.com/singularityware/docker2singularity#build-a-squashfs-image). I highly *don't* recommend this - it's masterfully messed up my computer when I've tried in random cases.

**Comment by cole-brokamp** [comment]
Going to stay away from that, then!  I found out that our HPC recently had singularity 3.0 installed.  So I'm giving it a go from there right now.  Do I need to be a sudoer to run `singularity-compose build`?  Its complaining to me that there is an issue building the container.

**Comment by vsoch** [comment]
okay - but if it's 3.0 exactly that's too early for a fully working example - likely a single container example will work, but not if they need to talk to one another. The same rules are true for Singularity - you can't build without sudo on a shared resource. You can try adding the fakeroot option to the file, but that's only available with 3.3.0 and later. So - I think you will need to test this on your local machine, because the cluster version is still too early :/

**Comment by cole-brokamp** [comment]
OK, thanks.  They are on 3.1. I'll try at home this evening.

**Comment by cole-brokamp** [comment]
all good with Singularity 3.3.0
